#!/usr/bin/env python3
update_date = "2025/05/18"
current_version = "1.2.10"
version_str = "?version=1133"

site_title = "シェル芸オンラインジャッジ / SHELLGEI ONLINE JUDGE"
summary_url = "https://yusukekato.jp/images/summary.jpg"
summary_large_url = "https://yusukekato.jp/images/summary_large_image.png"
main_url = "https://shellgei-online-judge.com"
blog_url = "https://yusukekato.jp"
site_description = "シェル芸オンラインジャッジはシェル芸用の問題と自動ジャッジシステムを提供するウェブサービスです。Shell-gei Online Judge is a website that provides problems and an automated judgment system."
favicon_url = main_url+"/favicon.jpg"
white_url = main_url+"/white.jpg"
black_url = main_url+"/black.jpg"
css_url = main_url+"/style.css"

def write_index_html(lang):
  lines = []

  if lang == "jp":
      print("lang: jp")
  if lang == "en":
      print("lang: en")
  
  # html, google
  lines.append('<!DOCTYPE html>\n')
  if lang == "jp":
    lines.append('<html lang="ja">\n')
  elif lang == "en":
    lines.append('<html lang="en">\n')
  lines.append('<head>\n')
  lines.append('<script async src="https://www.googletagmanager.com/gtag/js?id=G-L5F9JQGNP7"></script>\n')
  lines.append('<script>\n')
  lines.append('window.dataLayer = window.dataLayer || [];\n')
  lines.append('function gtag(){dataLayer.push(arguments);}\n')
  lines.append('gtag("js", new Date());\n')
  lines.append('gtag("config", "G-L5F9JQGNP7");\n')
  lines.append('</script>\n')
  lines.append('\n')

  # meta
  lines.append('<meta property="og:type" content="website" />\n')
  lines.append('<meta property="og:site_name" content="'+site_title+'" />\n')
  lines.append('<meta property="og:image" content="'+summary_url+'" />\n')
  lines.append('<meta name="twitter:card" content="summary_large_image" />\n')
  lines.append('<meta name="twitter:site" content="@yusukekato_main" />\n')
  lines.append('<meta name="twitter:title" content="'+site_title+'" />\n')
  lines.append('<meta name="twitter:image" content="'+summary_large_url+'" />\n')
  lines.append('<meta property="og:url" content="'+main_url+'" />\n')
  lines.append('<meta property="og:title" content="'+site_title+'" />\n')
  lines.append('<meta property="og:description" content="'+site_description+'" />\n')
  lines.append('<meta name="twitter:description" content="'+site_description+'" />\n')
  lines.append('<meta charset="utf-8">\n')
  lines.append('<meta name="description" content="'+site_description+'">\n')
  lines.append('<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">\n')
  lines.append('\n\n')

  # title, icon, fonts
  lines.append('<title>'+site_title+'</title>\n')
  lines.append('<link rel="icon" href="'+favicon_url+version_str+'">\n')
  lines.append('<link rel="stylesheet" href="'+css_url+version_str+'">\n')
  lines.append('<link rel="preconnect" href="https://fonts.googleapis.com">\n')
  lines.append('<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n')
  lines.append('<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&display=swap" rel="stylesheet">\n')
  lines.append('</head>\n')
  lines.append('\n')

  # heading
  lines.append('<body>\n')
  if lang == "jp":
    lines.append('<h1 class="heading-028" data-label="SHELLGEI ONLINE JUDGE">シェル・ワンライナーの遊び場</h1>\n')
  elif lang == "en":
    lines.append('<h1 class="heading-028" data-label="SHELLGEI ONLINE JUDGE">Shell one-liner playground</h1>\n')
  lines.append('<div class="alldiv">\n')
  lines.append('\n')

  # リストボタン生成
  lines.append('<ul class="nav-list">\n')
  lines.append('<li class="nav-list-item">\n')
  lines.append('<a href="'+main_url+'/index.html" class="bButton">JP</a>\n')
  lines.append('</li>\n')
  lines.append('<li class="nav-list-item">\n')
  lines.append('<a href="'+main_url+'/index.en.html" class="bButton">EN</a>\n')
  lines.append('</li>\n')
  lines.append('<li class="nav-list-item">\n')
  lines.append('<a href="https://github.com/YusukeKato/ShellgeiOnlineJudge" class="bButton">GitHub</a>\n')
  lines.append('</li>\n')
  lines.append('<li class="nav-list-item">\n')
  lines.append('<a href="'+blog_url+'" class="bButton">Blog</a>\n')
  lines.append('</li>\n')
  lines.append('</ul>\n')
  lines.append('\n')

  if lang == "jp":
    lines.append('<h2>概要</h2>\n')
  if lang == "en":
    lines.append('<h2>INFORMATION</h2>\n')

  # last updated
  if lang == "jp":
    lines.append('<h3>最終更新</h3>\n')
  elif lang == "en":
    lines.append('<h3>LAST UPDATED</h3>\n')
  lines.append('<ul>\n')
  lines.append('<li>- date: '+update_date+'</li>\n')
  lines.append('<li>- version: '+current_version+'</li>\n')
  lines.append('</ul>\n')
  lines.append('\n')

  # news
  if lang == "jp":
    lines.append('<h3>お知らせ</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>- 2024/12/27: 安定版バージョン1.1.0リリース</li>\n')
    lines.append('<li>- 2024/11/28: 回答例を追加</li>\n')
    lines.append('<li>- 2024/09/06: 画像問題を追加</li>\n')
    lines.append('<li>- 2024/05/03: シェル芸オンラインジャッジ一周年</li>\n')
    lines.append('<li>- 2024/04/24: 練習問題を追加</li>\n')
    lines.append('</ul>\n')
  elif lang == "en":
    lines.append('<h3>NEWS</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>- 2024/12/27: Release stable version 1.1.0</li>\n')
    lines.append('<li>- 2024/11/28: Added Example Answer</li>\n')
    lines.append('<li>- 2024/09/06: Added Image Problems</li>\n')
    lines.append('<li>- 2024/05/03: 1st Anniversary of SHELLGEI ONLINE JUDGE</li>\n')
    lines.append('<li>- 2024/04/24: Added Exercise Problems</li>\n')
    lines.append('</ul>\n')
  lines.append('<div class="slide">\n')
  lines.append('<img src="'+blog_url+'/images/news/news_20230503.jpg">\n')
  lines.append('<img src="'+blog_url+'/images/news/news_20240503.jpg">\n')
  lines.append('</div>\n')
  lines.append('<details>\n')
  if lang == "jp":
    lines.append('<summary>過去のお知らせ</summary>\n')
    lines.append('<ul>\n')
    lines.append('<li>- 2023/05/03: シェル芸オンラインジャッジ開始</li>\n')
    lines.append('</ul>\n')
  if lang == "en":
    lines.append('<summary>PREVIOUS NEWS</summary>\n')
    lines.append('<ul>\n')
    lines.append('<li>- 2023/05/03: Start of SHELLGEI ONLINE JUDGE</li>\n')
    lines.append('</ul>\n')
  lines.append('</details>\n')
  lines.append('\n')

  # information
  # about SHELLGEI ONLINE JUDGE
  if lang == "jp":
    lines.append('<h3>情報</h3>\n')
    lines.append('<details>\n')
    lines.append('<summary>このサイトとシェル芸について</summary>\n')
    lines.append('<h3>シェル芸オンラインジャッジとは</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>- シェル芸で問題を解いて遊べます</li>\n')
    lines.append('<li>- 出力結果の正誤判定も自動で行われます</li>\n')
    lines.append('<li>- このサイトはシェル芸非公式です</li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>シェル芸とは</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>- <a href="https://b.ueda.tech/?page=01434">シェル芸のトップページ</a>に情報があります</li>\n')
    lines.append('<li>- シェル芸とはCLI環境におけるシェルのワンライナーで様々なタスクをこなすことを指します</li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>シェル芸の例</h3>\n')
    lines.append('<p>Example 1: Output random String</p>\n')
    lines.append('<div class="codeClass"><pre><code class="mono-font2">head -c 65536 /dev/urandom | tr -dc a-zA-Z0-9 | cut -c -16</code></pre></div>\n')
    lines.append('<p>Example 2: Delete all .jpg files</p>\n')
    lines.append('<div class="codeClass"><pre><code class="mono-font2">find /tmp | grep .jpg$ | xargs -I@ rm @</code></pre></div>\n')
    lines.append('<h3>Shellgei Online Judge Repository</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>- <a href="https://github.com/YusukeKato/ShellgeiOnlineJudge">GitHub - ShellgeiOnlineJudge</a></li>\n')
    lines.append('<li>- <a href="https://github.com/YusukeKato/ShellgeiOnlineJudge/discussions">GitHub - SHELLGEI ONLINE JUDGE Discussions</a></li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>謝辞</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>下記のコンテンツを利用・参考にさせていただきました</li>\n')
    lines.append('<li>- <a href="https://github.com/theoremoon/ShellgeiBot-Image">theoremoon/ShellgeiBot-Image</a></li>\n')
    lines.append('<li>- <a href="https://github.com/ryuichiueda/ShellGeiData">ryuichiueda/ShellGeiData</a></li>\n')
    lines.append('<li>- <a href="https://github.com/jiro4989/websh">jiro4989/websh</a></li>\n')
    lines.append('<li>- <a href="https://judge.u-aizu.ac.jp/onlinejudge/">AIZU ONLINE JUDGE</a></li>\n')
    lines.append('<li>- <a href="https://atcoder.jp/">AtCoder</a></li>\n')
    lines.append('<li>- <a href="https://twitter.com/minyoruminyon">シェル芸bot</a></li>\n')
    lines.append('<li>- <a href="https://www.deepl.com/translator">DeepL</a></li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>遊び方</h3>\n')
    lines.append('<ol>\n')
    lines.append('<li>問題を選択</li>\n')
    lines.append('<li>シェル芸を記入</li>\n')
    lines.append('<li>シェル芸を実行</li>\n')
    lines.append('<li>正誤判定の結果を確認</li>\n')
    lines.append('</ol>\n')
    lines.append('</details>\n')
    lines.append('\n')
  elif lang == "en":
    lines.append('<h3>ABOUT</h3>\n')
    lines.append('<details>\n')
    lines.append('<summary>ABOUT THIS WEBSITE & SHELL-GEI</summary>\n')
    lines.append('<h3>About</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>- This website is a shell-gei unofficial</li>\n')
    lines.append('<li>- Solving problems with shell-gei</li>\n')
    lines.append('<li>- Automatic correct/incorrect judgment</li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>About shell-gei</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>- <a href="https://b.ueda.tech/?page=01434">Click here</a></li>\n')
    lines.append('<li>- Shell-gei is a shell one-liner in the CLI.</li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>Examples of shell-gei</h3>\n')
    lines.append('<p>Example 1: Output random String</p>\n')
    lines.append('<div class="codeClass"><pre><code class="mono-font2">head -c 65536 /dev/urandom | tr -dc a-zA-Z0-9 | cut -c -16</code></pre></div>\n')
    lines.append('<p>Example 2: Delete all .jpg files</p>\n')
    lines.append('<div class="codeClass"><pre><code class="mono-font2">find /tmp | grep .jpg$ | xargs -I@ rm @</code></pre></div>\n')
    lines.append('<h3>Shellgei Online Judge Repository</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>- <a href="https://github.com/YusukeKato/ShellgeiOnlineJudge">GitHub - ShellgeiOnlineJudge</a></li>\n')
    lines.append('<li>- <a href="https://github.com/YusukeKato/ShellgeiOnlineJudge/discussions">GitHub - SHELLGEI ONLINE JUDGE Discussions</a></li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>Thanks</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>Thanks to the following references.</li>\n')
    lines.append('<li>- <a href="https://github.com/theoremoon/ShellgeiBot-Image">theoremoon/ShellgeiBot-Image</a></li>\n')
    lines.append('<li>- <a href="https://github.com/ryuichiueda/ShellGeiData">ryuichiueda/ShellGeiData</a></li>\n')
    lines.append('<li>- <a href="https://github.com/jiro4989/websh">jiro4989/websh</a></li>\n')
    lines.append('<li>- <a href="https://judge.u-aizu.ac.jp/onlinejudge/">AIZU ONLINE JUDGE</a></li>\n')
    lines.append('<li>- <a href="https://atcoder.jp/">AtCoder</a></li>\n')
    lines.append('<li>- <a href="https://twitter.com/minyoruminyon">シェル芸bot</a></li>\n')
    lines.append('<li>- <a href="https://www.deepl.com/translator">DeepL</a></li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>How to play</h3>\n')
    lines.append('<ol>\n')
    lines.append('<li>Select problem</li>\n')
    lines.append('<li>Write shell-gei</li>\n')
    lines.append('<li>Run shell-gei</li>\n')
    lines.append('<li>Check correct/incorrect</li>\n')
    lines.append('</ol>\n')
    lines.append('</details>\n')
    lines.append('\n')

  # update history
  lines.append('<details>\n')
  if lang == "jp":
    lines.append('<summary>更新履歴</summary>\n')
  if lang == "en":
    lines.append('<summary>UPDATE HISTORY</summary>\n')
  lines.append('<ul>\n')
  if lang == "jp":
    lines.append('<li>シェル芸オンラインジャッジの更新履歴です</li>\n')
  if lang == "en":
    lines.append('<li>Update history of SHELLGEI ONLINE JUDGE.</li>\n')
  lines.append('</ul>\n')
  lines.append('<details>\n')
  lines.append('<summary>2025</summary>\n')
  lines.append('<ul>\n')
  lines.append('<li>- 05/18: サーバ更新、Dockerイメージの更新</li>\n')
  lines.append('<li>- 04/05: サーバ更新、Dockerイメージの更新</li>\n')
  lines.append('<li>- 03/08: サーバメンテナンス、問題選択ボタンをアップデート</li>\n')
  lines.append('<li>- 02/23: コマンド入力ボタンを追加、ボタンのサイズ調整、通常問題50を追加</li>\n')
  lines.append('<li>- 02/22: 問題選択ボタンを追加、通常問題49を追加</li>\n')
  lines.append('<li>- 02/16: サーバメンテナンス</li>\n')
  lines.append('<li>- 01/04: GENERAL-48追加</li>\n')
  lines.append('<li>- 01/02: サーバメンテナンス、問題追加</li>\n')
  lines.append('</ul>\n')
  lines.append('</details>\n')
  lines.append('<details>\n')
  lines.append('<summary>2024</summary>\n')
  lines.append('<ul>\n')
  lines.append('<li>- 12/27: 安定版1.1.0リリース</li>\n')
  lines.append('<li>- 12/26: 全問題のテスト作成、answerフォルダ作成</li>\n')
  lines.append('<li>- 12/22: サーバメンテナンス</li>\n')
  lines.append('<li>- 11/29: GIF画像に対応</li>\n')
  lines.append('<li>- 11/28: news追加</li>\n')
  lines.append('<li>- 11/27: GENERALの回答例を追加、正誤判定を修正</li>\n')
  lines.append('<li>- 11/24: concatとcowsayを削除</li>\n')
  lines.append('<li>- 11/23: ドキュメントのメンテナンス</li>\n')
  lines.append('<li>- 11/22: ドキュメントのメンテナンス</li>\n')
  lines.append('<li>- 11/21: リポジトリを一つにまとめる、ローカル環境でテスト可能に</li>\n')
  lines.append('<li>- 11/04: テスト追加、HTTPS更新、問題数表示</li>\n')
  lines.append('<li>- 11/02: 正誤判定の処理をサーバ側へ移動（完了）</li>\n')
  lines.append('<li>- 10/28: 正誤判定の処理をサーバ側へ移動</li>\n')
  lines.append('<li>- 10/22: 問題選択にバグがあったので修正</li>\n')
  lines.append('<li>- 10/20: コマンドを入力するボタンを設置</li>\n')
  lines.append('<li>- 10/16: Ctrl+Enterでシェル芸を実行できる機能追加</li>\n')
  lines.append('<li>- 10/14: ジャッジ修正（正誤判定で必ず正解になる問題の解決）</li>\n')
  lines.append('<li>- 10/01: メンテナンス、HTTPS更新</li>\n')
  lines.append('<li>- 09/07: テキスト修正</li>\n')
  lines.append('<li>- 09/06: 画像生成問題追加</li>\n')
  lines.append('<li>- 09/04: メンテナンス一旦完了、システム全体を見直し</li>\n')
  lines.append('<li>- 09/03: ブラウザ側のアプリを整理</li>\n')
  lines.append('<li>- 09/01: JavaScript側でもボタンの連打防止</li>\n')
  lines.append('<li>- 08/31: 全体を整理, 連続実行の予防</li>\n')
  lines.append('<li>- 08/27: 問題集データを整理</li>\n')
  lines.append('<li>- 08/26: 問題集データのリンクを追加</li>\n')
  lines.append('<li>- 08/25: 日本語と英語を分ける、SSL証明書更新、問題追加</li>\n')
  lines.append('<li>- 08/11: 微修正</li>\n')
  lines.append('<li>- 08/07: SSL証明書更新</li>\n')
  lines.append('<li>- 07/18: SSL証明書更新</li>\n')
  lines.append('<li>- 06/14: 練習問題wc,uniqを追加、SSL証明書更新</li>\n')
  lines.append('<li>- 05/27: 練習問題sortを追加</li>\n')
  lines.append('<li>- 05/25: 練習問題sortを追加</li>\n')
  lines.append('<li>- 05/23: 練習問題awkを追加</li>\n')
  lines.append('<li>- 05/17: 練習問題awkを追加</li>\n')
  lines.append('<li>- 05/15: 誤字脱字を修正、練習問題awkを追加</li>\n')
  lines.append('<li>- 05/13: 練習問題awkを追加、等幅フォント指定</li>\n')
  lines.append('<li>- 05/12: 練習問題grepを追加</li>\n')
  lines.append('<li>- 05/11: 練習問題findを追加</li>\n')
  lines.append('<li>- 05/06: 練習問題sedを追加</li>\n')
  lines.append('<li>- 05/05: デザイン微修正、SSL証明書更新、練習問題catを追加</li>\n')
  lines.append('<li>- 05/04: お知らせのレイアウトを更新、シェル芸IDを追加</li>\n')
  lines.append('<li>- 05/03: 一周年、お知らせを追加</li>\n')
  lines.append('<li>- 05/02: 問題タイトル修正、問41と問42を追加</li>\n')
  lines.append('<li>- 05/01: デザイン修正</li>\n')
  lines.append('<li>- 04/30: 拡大表示不可、その他微修正</li>\n')
  lines.append('<li>- 04/29: システム修正、レイアウト修正</li>\n')
  lines.append('<li>- 04/28: 説明文を微修正</li>\n')
  lines.append('<li>- 04/27: レイアウト調整</li>\n')
  lines.append('<li>- 04/26: フォント指定</li>\n')
  lines.append('<li>- 04/25: 練習問題echo、実行環境、シェル芸の例を追加</li>\n')
  lines.append('<li>- 04/24: 練習問題の項目を追加</li>\n')
  lines.append('<li>- 04/23: レイアウト修正</li>\n')
  lines.append('<li>- 04/22: レイアウト修正</li>\n')
  lines.append('<li>- 04/21: 問39、問40を追加、デザイン修正</li>\n')
  lines.append('<li>- 04/20: システムを修正、英語対応（？）</li>\n')
  lines.append('<li>- 04/17: サーバ側の処理を修正、タイムアウト機能修正</li>\n')
  lines.append('<li>- 04/13: 更新履歴作成、画像のリンク修正</li>\n')
  lines.append('<li>- 03/05: SSL証明書更新</li>\n')
  lines.append('</ul>\n')
  lines.append('</details>\n')
  lines.append('<details>\n')
  lines.append('<summary>2023</summary>\n')
  lines.append('<ul>\n')
  lines.append('<li>- 11/10: 問題追加</li>\n')
  lines.append('<li>- 10/01: 問題追加</li>\n')
  lines.append('<li>- 09/02: 問題追加</li>\n')
  lines.append('<li>- 08/06: 問題追加</li>\n')
  lines.append('<li>- 07/01: 問題追加</li>\n')
  lines.append('<li>- 06/03: 問題追加</li>\n')
  lines.append('<li>- 05/20: 問題追加</li>\n')
  lines.append('<li>- 05/13: 問題追加、レイアウト修正</li>\n')
  lines.append('<li>- 05/07: 問題追加、HTMLタグに対応</li>\n')
  lines.append('<li>- 05/03: サービス開始</li>\n')
  lines.append('</ul>\n')
  lines.append('</details>\n')
  lines.append('</details>\n')
  lines.append('\n')

  # contact
  if lang == "jp":
    lines.append('<details>\n')
    lines.append('<summary>お問い合わせ</summary>\n')
    lines.append('<h3>SNS</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>- X/Twitter：<a href="https://twitter.com/yusukekato_main">@yusukekato_main</a></li>\n')
    lines.append('<li>- タグ：#シェル芸オンラインジャッジ</li>\n')
    lines.append('<li>- mixi2：<a href="https://mixi.social/communities/dcf8e9d8-a6c4-40a9-8e05-328b4424f886/about">シェル芸オンラインジャッジのコミュニティ</a></li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>GitHub</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>- <a href="https://github.com/YusukeKato/ShellgeiOnlineJudge/discussions">GitHub - Discussions</a></li>\n')
    lines.append('<li>- <a href="https://github.com/YusukeKato/ShellgeiOnlineJudge/issues">GitHub - Issues</a></li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>Author</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>- GitHub : <a href="https://github.com/YusukeKato">YusukeKato</a></li>\n')
    lines.append('<li>- Blog : <a href="https://yusukekato.jp/">yusukekato.jp</a></li>\n')
    lines.append('</ul>\n')
    lines.append('</details>\n')
    lines.append('\n')
  if lang == "en":
    lines.append('<details>\n')
    lines.append('<summary>CONTACT</summary>\n')
    lines.append('<h3>SNS</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>- X/Twitter: <a href="https://twitter.com/yusukekato_main">@yusukekato_main</a></li>\n')
    lines.append('<li>- hashtag: #ShellgeiOnlineJudge</li>\n')
    lines.append('<li>- mixi2: <a href="https://mixi.social/communities/dcf8e9d8-a6c4-40a9-8e05-328b4424f886/about">community</a></li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>GitHub</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>- <a href="https://github.com/YusukeKato/ShellgeiOnlineJudge/discussions">GitHub - Discussions</a></li>\n')
    lines.append('<li>- <a href="https://github.com/YusukeKato/ShellgeiOnlineJudge/issues">GitHub - Issues</a></li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>Author</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>- GitHub : <a href="https://github.com/YusukeKato">YusukeKato</a></li>\n')
    lines.append('<li>- Blog : <a href="https://yusukekato.jp/">yusukekato.jp</a></li>\n')
    lines.append('</ul>\n')
    lines.append('</details>\n')
    lines.append('\n')

  # others
  if lang == "jp":
    lines.append('<details>\n')
    lines.append('<summary>その他</summary>\n')
    lines.append('<h3>注意事項</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>- Google AnalyticsとGoogle Search Consoleを利用しています</li>\n')
    lines.append('<li>- このウェブサイトの利用によって生じる損害等について一切責任を負いません</li>\n')
    lines.append('<li>- 実行されたコマンドなどの情報は全て記録されます</li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>回答例</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>問題を解いていただき、誠にありがとうございます</li>\n')
    lines.append('<li>- <a href="https://gist.github.com/eggplants/71c0459f38028938a15d35b19bab47b5">eggplants/ans.csv</a></li>\n')
    lines.append('<li>- <a href="https://shellgei.wiki/?cat=5">シェル芸非公式WIKI</a></li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>おすすめ</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>さらに難しい問題や面白い問題が解きたい方には以下がおすすめです</li>\n')
    lines.append('<li>- <a href="https://b.ueda.tech/?page=00684">シェル芸勉強会問題一覧</a></li>\n')
    lines.append('<li>- <a href="https://atcoder.jp/">AtCoder（競技プログラミング）</a></li>\n')
    lines.append('</ul>\n')
    lines.append('</details>\n')
    lines.append('\n')
  if lang == "en":
    lines.append('<details>\n')
    lines.append('<summary>OTHERS</summary>\n')
    lines.append('<h3>Attention</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>- This website Use Google Analytics and Google Search Console</li>\n')
    lines.append('<li>- I am not responsible for any damage or loss caused by the use of this website</li>\n')
    lines.append('<li>- Log such as executed commands is recorded</li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>Example answer</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>Thanks for solving problems</li>\n')
    lines.append('<li>- <a href="https://gist.github.com/eggplants/71c0459f38028938a15d35b19bab47b5">eggplants/ans.csv</a></li>\n')
    lines.append('<li>- <a href="https://shellgei.wiki/?cat=5">シェル芸非公式WIKI</a></li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>Recommendation</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>List of recommendations</li>\n')
    lines.append('<li>- <a href="https://b.ueda.tech/?page=00684">シェル芸勉強会問題一覧</a></li>\n')
    lines.append('<li>- <a href="https://atcoder.jp/">AtCoder（競技プログラミング）</a></li>\n')
    lines.append('</ul>\n')
    lines.append('</details>\n')
    lines.append('\n')

  # answer
  if lang == "jp":
    lines.append('<h3>回答例</h3>\n')
  elif lang == "en":
    lines.append('<h3>Answer</h3>\n')

  # general answer
  lines.append('<details>\n')
  lines.append('<summary>GENERAL</summary>\n')
  lines.append('\n')
  f_cnt_general_num = open('../../data/scripts/cnt_general_num.txt', 'r', encoding='UTF-8')
  cnt_general_num = f_cnt_general_num.read().replace("\n","")
  for i in range(int(cnt_general_num)):
    if i % 10 == 0:
      if i != 0:
        lines.append('</details>\n')
      lines.append('<details>\n')
      lines.append('<summary>' + str(i+1) + ' - ' + str(i+10) + '</summary>\n')
    file_name = "GENERAL-" + str(i+1).zfill(8)
    f_answer = open('../../data/answer/'+ file_name +'.txt', 'r', encoding='UTF-8')
    answer_shellgei = f_answer.read().replace("<", "&lt;").replace(">", "&gt;")
    lines.append('<p>'+ str(i+1) + '</p>\n')
    lines.append('<div class="codeClass"><pre><code class="mono-font2">' + answer_shellgei + '</code></pre></div>\n')
    if i == int(cnt_general_num) - 1:
      lines.append('</details>\n')
  lines.append('</details>\n') # general answer
  lines.append('\n')

  # exercise answer
  lines.append('<details>\n')
  lines.append('<summary>EXERCISE</summary>\n')
  lines.append('\n')
  cmd_list = ["awk", "cat", "echo", "find", "grep", "sed", "sort", "uniq", "wc"]
  for j in range(len(cmd_list)):
    f_cnt_exercise_num = open('../../data/scripts/cnt_exercise_' + cmd_list[j] + '_num.txt', 'r', encoding='UTF-8')
    cnt_exercise_num = f_cnt_exercise_num.read().replace("\n","")
    lines.append('<details>\n')
    lines.append('<summary>' + cmd_list[j] + '</summary>\n')
    for i in range(int(cnt_exercise_num)):
      file_name = "EXERCISE-" + cmd_list[j] + "-" + str(i+1).zfill(2)
      f_answer = open('../../data/answer/'+ file_name +'.txt', 'r', encoding='UTF-8')
      answer_shellgei = f_answer.read().replace("<", "&lt;").replace(">", "&gt;")
      lines.append('<p>'+ str(i+1) + '</p>\n')
      lines.append('<div class="codeClass"><pre><code class="mono-font2">' + answer_shellgei + '</code></pre></div>\n')
    lines.append('</details>\n')
  lines.append('</details>\n') # exercise answer
  lines.append('\n')

  # image answer
  lines.append('<details>\n')
  lines.append('<summary>IMAGE</summary>\n')
  lines.append('\n')
  f_cnt_image_num = open('../../data/scripts/cnt_image_num.txt', 'r', encoding='UTF-8')
  cnt_image_num = f_cnt_image_num.read().replace("\n","")
  for i in range(int(cnt_image_num)):
    if i % 10 == 0:
      if i != 0:
        lines.append('</details>\n')
      lines.append('<details>\n')
      lines.append('<summary>' + str(i+1) + ' - ' + str(i+10) + '</summary>\n')
    file_name = "IMAGE-" + str(i+1).zfill(8)
    f_answer = open('../../data/answer/'+ file_name +'.txt', 'r', encoding='UTF-8')
    answer_shellgei = f_answer.read().replace("<", "&lt;").replace(">", "&gt;")
    lines.append('<p>'+ str(i+1) + '</p>\n')
    lines.append('<div class="codeClass"><pre><code class="mono-font2">' + answer_shellgei + '</code></pre></div>\n')
    if i == int(cnt_image_num) - 1:
      lines.append('</details>\n')
  lines.append('</details>\n') # image answer
  lines.append('\n')

  # select general problem
  if lang == "jp":
    lines.append('<h2>問題選択</h2>\n')
    lines.append('<h3 id="generalProblem">通常問題</h3>\n')
    lines.append('<div class="centerClass">\n')
    lines.append('<label class="selectbox">\n')
    lines.append('<select class="selectClass" id="selectForm1">\n')
    lines.append('<option value="GENERAL-00000001" selected>1 : 出力テスト</option>\n')
    lines.append('<option value="GENERAL-00000002">2 : 入力テスト</option>\n')
    lines.append('<option value="GENERAL-00000003">3 : 改行テスト</option>\n')
    lines.append('<option value="GENERAL-00000004">4 : 足し算</option>\n')
    lines.append('<option value="GENERAL-00000005">5 : フィボナッチ数列</option>\n')
    lines.append('<option value="GENERAL-00000006">6 : 円周率10桁</option>\n')
    lines.append('<option value="GENERAL-00000007">7 : 円周率100桁</option>\n')
    lines.append('<option value="GENERAL-00000008">8 : 鶴亀算</option>\n')
    lines.append('<option value="GENERAL-00000009">9 : 日記の並べ替え</option>\n')
    lines.append('<option value="GENERAL-00000010">10 : 虫食い日記</option>\n')
    lines.append('<option value="GENERAL-00000011">11 : 行列の回転</option>\n')
    lines.append('<option value="GENERAL-00000012">12 : ビットの反転</option>\n')
    lines.append('<option value="GENERAL-00000013">13 : アルファベットの調査</option>\n')
    lines.append('<option value="GENERAL-00000014">14 : グループ分け</option>\n')
    lines.append('<option value="GENERAL-00000015">15 : 素数判定</option>\n')
    lines.append('<option value="GENERAL-00000016">16 : HTMLテスト</option>\n')
    lines.append('<option value="GENERAL-00000017">17 : ソート1</option>\n')
    lines.append('<option value="GENERAL-00000018">18 : 二分探索</option>\n')
    lines.append('<option value="GENERAL-00000019">19 : 元の文字列</option>\n')
    lines.append('<option value="GENERAL-00000020">20 : 素因数分解</option>\n')
    lines.append('<option value="GENERAL-00000021">21 : 回文判定</option>\n')
    lines.append('<option value="GENERAL-00000022">22 : 2の1024乗</option>\n')
    lines.append('<option value="GENERAL-00000023">23 : スコア計算</option>\n')
    lines.append('<option value="GENERAL-00000024">24 : ナップサック問題</option>\n')
    lines.append('<option value="GENERAL-00000025">25 : 文字列の組み合わせ</option>\n')
    lines.append('<option value="GENERAL-00000026">26 : 最短経路探索</option>\n')
    lines.append('<option value="GENERAL-00000027">27 : 電車の乗り換え</option>\n')
    lines.append('<option value="GENERAL-00000028">28 : 模様の描画1</option>\n')
    lines.append('<option value="GENERAL-00000029">29 : 模様の描画2</option>\n')
    lines.append('<option value="GENERAL-00000030">30 : シーザー暗号</option>\n')
    lines.append('<option value="GENERAL-00000031">31 : 最大公約数</option>\n')
    lines.append('<option value="GENERAL-00000032">32 : 最小公倍数</option>\n')
    lines.append('<option value="GENERAL-00000033">33 : 文字カウント1</option>\n')
    lines.append('<option value="GENERAL-00000034">34 : xの5乗</option>\n')
    lines.append('<option value="GENERAL-00000035">35 : 文字列の複製</option>\n')
    lines.append('<option value="GENERAL-00000036">36 : NをN回出力</option>\n')
    lines.append('<option value="GENERAL-00000037">37 : 数字の抽出</option>\n')
    lines.append('<option value="GENERAL-00000038">38 : 割り算判定</option>\n')
    lines.append('<option value="GENERAL-00000039">39 : 重複削除</option>\n')
    lines.append('<option value="GENERAL-00000040">40 : 文字カウント2</option>\n')
    lines.append('<option value="GENERAL-00000041">41 : 魔法陣3x3</option>\n')
    lines.append('<option value="GENERAL-00000042">42 : 魔法陣5x5</option>\n')
    lines.append('<option value="GENERAL-00000043">43 : 文字列の複製2</option>\n')
    lines.append('<option value="GENERAL-00000044">44 : 文字列の検索</option>\n')
    lines.append('<option value="GENERAL-00000045">45 : 模様の描画3</option>\n')
    lines.append('<option value="GENERAL-00000046">46 : 単位行列の生成</option>\n')
    lines.append('<option value="GENERAL-00000047">47 : IPアドレスの抽出</option>\n')
    lines.append('<option value="GENERAL-00000048">48 : 文字列の圧縮</option>\n')
    lines.append('<option value="GENERAL-00000049">49 : 最大文字数の回文調査</option>\n')
    lines.append('<option value="GENERAL-00000050">50 : 四則演算</option>\n')
    lines.append('</select>\n')
    lines.append('</label>\n')
    lines.append('<p></p>\n')
    lines.append('</div>\n') # div centerClass
    lines.append('<div class="centerClass">\n')
    lines.append('<table>\n')
    lines.append('<tr>\n')
    lines.append('<td><input type="button" value="<" class="buttonClass_s" id="selectPre1"></td>\n')
    lines.append('<td><input type="button" value="決定" class="buttonClass" id="selectButton1"></td>\n')
    lines.append('<td><input type="button" value=">" class="buttonClass_s" id="selectNext1"></td>\n')
    lines.append('</tr>\n')
    lines.append('</table>\n')
    lines.append('</div>\n') # div centerClass
    lines.append('\n')
  if lang == "en":
    lines.append('<h2>Select Problem</h2>\n')
    lines.append('<h3 id="generalProblem">General</h3>\n')
    lines.append('<div class="centerClass">\n')
    lines.append('<label class="selectbox">\n')
    lines.append('<select class="selectClass" id="selectForm1">\n')
    lines.append('<option value="GENERAL-00000001" selected>1 : Test: Output</option>\n')
    lines.append('<option value="GENERAL-00000002">2 : Test: Input</option>\n')
    lines.append('<option value="GENERAL-00000003">3 : Test: Newline</option>\n')
    lines.append('<option value="GENERAL-00000004">4 : Add</option>\n')
    lines.append('<option value="GENERAL-00000005">5 : Fibonacci</option>\n')
    lines.append('<option value="GENERAL-00000006">6 : PI 10</option>\n')
    lines.append('<option value="GENERAL-00000007">7 : PI 100</option>\n')
    lines.append('<option value="GENERAL-00000008">8 : Crane &amp; Turtle</option>\n')
    lines.append('<option value="GENERAL-00000009">9 : Diary in Pieces</option>\n')
    lines.append('<option value="GENERAL-00000010">10 : Blank Diary</option>\n')
    lines.append('<option value="GENERAL-00000011">11 : Matrix Rotation</option>\n')
    lines.append('<option value="GENERAL-00000012">12 : Bit Inversion</option>\n')
    lines.append('<option value="GENERAL-00000013">13 : Check Alphabet</option>\n')
    lines.append('<option value="GENERAL-00000014">14 : Grouping</option>\n')
    lines.append('<option value="GENERAL-00000015">15 : Judge Prime Number</option>\n')
    lines.append('<option value="GENERAL-00000016">16 : Test: HTML Tag</option>\n')
    lines.append('<option value="GENERAL-00000017">17 : Sort 1</option>\n')
    lines.append('<option value="GENERAL-00000018">18 : Binary Search</option>\n')
    lines.append('<option value="GENERAL-00000019">19 : String Iteration</option>\n')
    lines.append('<option value="GENERAL-00000020">20 : Prime Factorization</option>\n')
    lines.append('<option value="GENERAL-00000021">21 : Palindrome</option>\n')
    lines.append('<option value="GENERAL-00000022">22 : 2^1024</option>\n')
    lines.append('<option value="GENERAL-00000023">23 : Score Calculation</option>\n')
    lines.append('<option value="GENERAL-00000024">24 : Knapsack Problem</option>\n')
    lines.append('<option value="GENERAL-00000025">25 : Combine String</option>\n')
    lines.append('<option value="GENERAL-00000026">26 : Shortest Path Search</option>\n')
    lines.append('<option value="GENERAL-00000027">27 : Timetable</option>\n')
    lines.append('<option value="GENERAL-00000028">28 : Pattern 1</option>\n')
    lines.append('<option value="GENERAL-00000029">29 : Pattern 2</option>\n')
    lines.append('<option value="GENERAL-00000030">30 : Caesar Cipher</option>\n')
    lines.append('<option value="GENERAL-00000031">31 : GCD</option>\n')
    lines.append('<option value="GENERAL-00000032">32 : LCM</option>\n')
    lines.append('<option value="GENERAL-00000033">33 : Charactor Count 1</option>\n')
    lines.append('<option value="GENERAL-00000034">34 : x^5</option>\n')
    lines.append('<option value="GENERAL-00000035">35 : Copy String</option>\n')
    lines.append('<option value="GENERAL-00000036">36 : Output Number</option>\n')
    lines.append('<option value="GENERAL-00000037">37 : Extracting Number</option>\n')
    lines.append('<option value="GENERAL-00000038">38 : Divisible?</option>\n')
    lines.append('<option value="GENERAL-00000039">39 : Delete Duplicates</option>\n')
    lines.append('<option value="GENERAL-00000040">40 : Charactor Count 2</option>\n')
    lines.append('<option value="GENERAL-00000041">41 : Magic Square 3x3</option>\n')
    lines.append('<option value="GENERAL-00000042">42 : Magic Square 5x5</option>\n')
    lines.append('<option value="GENERAL-00000043">43 : Copy String 2</option>\n')
    lines.append('<option value="GENERAL-00000044">44 : Search String</option>\n')
    lines.append('<option value="GENERAL-00000045">45 : Pattern 3</option>\n')
    lines.append('<option value="GENERAL-00000046">46 : Create Identity Matrix</option>\n')
    lines.append('<option value="GENERAL-00000047">47 : IP address extraction</option>\n')
    lines.append('<option value="GENERAL-00000048">48 : String compression</option>\n')
    lines.append('<option value="GENERAL-00000049">49 : Find longest palindromes</option>\n')
    lines.append('<option value="GENERAL-00000050">50 : +-*/</option>\n')
    lines.append('</select>\n')
    lines.append('</label>\n')
    lines.append('<p></p>\n')
    lines.append('</div>\n')
    lines.append('<div class="centerClass">\n')
    lines.append('<table>\n')
    lines.append('<tr>\n')
    lines.append('<td><input type="button" value="<" class="buttonClass_s" id="selectPre1"></td>\n')
    lines.append('<td><input type="button" value="GO" class="buttonClass" id="selectButton1"></td>\n')
    lines.append('<td><input type="button" value=">" class="buttonClass_s" id="selectNext1"></td>\n')
    lines.append('</tr>\n')
    lines.append('</table>\n')
    lines.append('</div>\n')
    lines.append('\n')

  # select exercize problem
  if lang == "jp":
    lines.append('<h3 id="exerciseProblem">練習問題</h3>\n')
  if lang == "en":
    lines.append('<h3 id="exerciseProblem">Exercise</h3>\n')
  lines.append('<div class="centerClass">\n')
  lines.append('<label class="selectbox">\n')
  lines.append('<select class="selectClass" id="selectForm2">\n')
  lines.append('<option value="EXERCISE-echo-01" selected>1-1 : echo 1</option>\n')
  lines.append('<option value="EXERCISE-echo-02">1-2 : echo 2</option>\n')
  lines.append('<option value="EXERCISE-echo-03">1-3 : echo 3</option>\n')
  lines.append('<option value="EXERCISE-cat-01">2-1 : cat 1</option>\n')
  lines.append('<option value="EXERCISE-cat-02">2-2 : cat 2</option>\n')
  lines.append('<option value="EXERCISE-cat-03">2-3 : cat 3</option>\n')
  lines.append('<option value="EXERCISE-cat-04">2-4 : cat 4</option>\n')
  lines.append('<option value="EXERCISE-sed-01">3-1 : sed 1</option>\n')
  lines.append('<option value="EXERCISE-sed-02">3-2 : sed 2</option>\n')
  lines.append('<option value="EXERCISE-sed-03">3-3 : sed 3</option>\n')
  lines.append('<option value="EXERCISE-sed-04">3-4 : sed 4</option>\n')
  lines.append('<option value="EXERCISE-sed-05">3-5 : sed 5</option>\n')
  lines.append('<option value="EXERCISE-sed-06">3-6 : sed 6</option>\n')
  lines.append('<option value="EXERCISE-find-01">4-1 : find 1</option>\n')
  lines.append('<option value="EXERCISE-find-02">4-2 : find 2</option>\n')
  lines.append('<option value="EXERCISE-find-03">4-3 : find 3</option>\n')
  lines.append('<option value="EXERCISE-grep-01">5-1 : grep 1</option>\n')
  lines.append('<option value="EXERCISE-grep-02">5-2 : grep 2</option>\n')
  lines.append('<option value="EXERCISE-grep-03">5-3 : grep 3</option>\n')
  lines.append('<option value="EXERCISE-grep-04">5-4 : grep 4</option>\n')
  lines.append('<option value="EXERCISE-awk-01">6-1 : awk 1</option>\n')
  lines.append('<option value="EXERCISE-awk-02">6-2 : awk 2</option>\n')
  lines.append('<option value="EXERCISE-awk-03">6-3 : awk 3</option>\n')
  lines.append('<option value="EXERCISE-awk-04">6-4 : awk 4</option>\n')
  lines.append('<option value="EXERCISE-awk-05">6-5 : awk 5</option>\n')
  lines.append('<option value="EXERCISE-awk-06">6-6 : awk 6</option>\n')
  lines.append('<option value="EXERCISE-sort-01">7-1 : sort 1</option>\n')
  lines.append('<option value="EXERCISE-sort-02">7-2 : sort 2</option>\n')
  lines.append('<option value="EXERCISE-sort-03">7-3 : sort 3</option>\n')
  lines.append('<option value="EXERCISE-wc-01">8-1 : wc 1</option>\n')
  lines.append('<option value="EXERCISE-wc-02">8-2 : wc 2</option>\n')
  lines.append('<option value="EXERCISE-wc-03">8-3 : wc 3</option>\n')
  lines.append('<option value="EXERCISE-uniq-01">9-1 : uniq 1</option>\n')
  lines.append('<option value="EXERCISE-uniq-02">9-2 : uniq 2</option>\n')
  lines.append('</select>\n')
  lines.append('</label>\n')
  lines.append('<p></p>\n')
  lines.append('</div>\n')
  lines.append('<div class="centerClass">\n')
  lines.append('<table>\n')
  lines.append('<tr>\n')
  lines.append('<td><input type="button" value="<" class="buttonClass_s" id="selectPre2"></td>\n')
  if lang == "jp":
    lines.append('<td><input type="button" value="決定" class="buttonClass" id="selectButton2"></td>\n')
  if lang == "en":
    lines.append('<td><input type="button" value="GO" class="buttonClass" id="selectButton2"></td>\n')
  lines.append('<td><input type="button" value=">" class="buttonClass_s" id="selectNext2"></td>\n')
  lines.append('</tr>\n')
  lines.append('</table>\n')
  lines.append('</div>\n')
  lines.append('\n')

  # select image problem
  if lang == "jp":
    lines.append('<h3 id="imageProblem">画像問題</h3>\n')
  if lang == "en":
    lines.append('<h3 id="imageProblem">Image</h3>\n')
  lines.append('<div class="centerClass">\n')
  lines.append('<label class="selectbox">\n')
  lines.append('<select class="selectClass" id="selectForm3">\n')
  if lang == "jp":
    lines.append('<option value="IMAGE-00000001" selected>1: 画像テスト</option>\n')
    lines.append('<option value="IMAGE-00000002">2: 横線</option>\n')
    lines.append('<option value="IMAGE-00000003">3: 円</option>\n')
    lines.append('<option value="IMAGE-00000004">4: 市松模様</option>\n')
    lines.append('<option value="IMAGE-00000005">5: 四角</option>\n')
  if lang == "en":
    lines.append('<option value="IMAGE-00000001">1: Image Test</option>\n')
    lines.append('<option value="IMAGE-00000002">2: Draw Line</option>\n')
    lines.append('<option value="IMAGE-00000003">3: Draw Circle</option>\n')
    lines.append('<option value="IMAGE-00000004">4: Draw Checkered Pattern</option>\n')
    lines.append('<option value="IMAGE-00000005">5: Draw Square</option>\n')
  lines.append('</select>\n')
  lines.append('</label>\n')
  lines.append('<p></p>\n')
  lines.append('</div>\n')
  lines.append('<div class="centerClass">\n')
  lines.append('<div class="tableClass">\n')
  lines.append('<table>')
  lines.append('<tr>')
  lines.append('<td><input type="button" value="<" class="buttonClass_s" id="selectPre3"></td>\n')
  if lang == "jp":
    lines.append('<td><input type="button" value="決定" class="buttonClass" id="selectButton3"></td>\n')
  if lang == "en":
    lines.append('<td><input type="button" value="GO" class="buttonClass" id="selectButton3"></td>\n')
  lines.append('<td><input type="button" value=">" class="buttonClass_s" id="selectNext3"></td>\n')
  lines.append('</tr>')
  lines.append('</table>')
  lines.append('</div>\n')
  lines.append('</div>\n')
  lines.append('\n')

  # selected
  if lang == "jp":
    lines.append('<h3>選択した問題ID</h3>\n')
  if lang == "en":
    lines.append('<h3>Selected Problem ID</h3>\n')
  lines.append('<div class="textClass">\n')
  lines.append('<pre><code id="selectedText" class="mono-font">NULL</code></pre>\n')
  lines.append('</div>\n')

  # problem info
  if lang == "jp":
    lines.append('<h2>問題</h2>\n')
    lines.append('<h3>問題文</h3>\n')
    lines.append('<div class="textClass">\n')
    lines.append('<pre><code id="problemText" class="mono-font">NULL</code></pre>\n')
    lines.append('</div>\n')
    lines.append('<h3>入力</h3>\n')
    lines.append('<div class="textClass">\n')
    lines.append('<pre><code id="inputText" class="mono-font">NULL</code></pre>\n')
    lines.append('</div>\n')
    lines.append('<h3>想定出力</h3>\n')
    lines.append('<div class="textClass">\n')
    lines.append('<pre><code id="outputText" class="mono-font">NULL</code></pre>\n')
    lines.append('</div>\n')
    lines.append('<h3>想定画像</h3>\n')
    lines.append('<div class="img" id="outputImage">\n')
    # lines.append('<img id="outputImage" src="'+black_url+'" alt="output image">\n')
    lines.append('</div>\n')
    lines.append('\n')
  if lang == "en":
    lines.append('<h2>Problem</h2>\n')
    lines.append('<h3>Problem Statement</h3>\n')
    lines.append('<div class="textClass">\n')
    lines.append('<pre><code id="problemText" class="mono-font">NULL</code></pre>\n')
    lines.append('</div>\n')
    lines.append('<h3>Input</h3>\n')
    lines.append('<div class="textClass">\n')
    lines.append('<pre><code id="inputText" class="mono-font">NULL</code></pre>\n')
    lines.append('</div>\n')
    lines.append('<h3>Expected Output</h3>\n')
    lines.append('<div class="textClass">\n')
    lines.append('<pre><code id="outputText" class="mono-font">NULL</code></pre>\n')
    lines.append('</div>\n')
    lines.append('<h3>Expected Output Image</h3>\n')
    lines.append('<div class="img" id="outputImage">\n')
    #lines.append('<img id="outputImage" src="'+black_url+'" alt="output image">\n')
    lines.append('</div>\n')
    lines.append('\n')

  # run
  if lang == "jp":
    lines.append('<h2>実行</h2>\n')
    lines.append('<details>\n')
    lines.append('<summary>注意点</summary>\n')
    lines.append('<h3>注意点</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>入力の取得 : "cat input.txt"</li>\n')
    lines.append('<li>画像の出力 : "media/output.jpg"</li>\n')
    lines.append('<li>出力は想定出力&想定画像と一致すること</li>\n')
    lines.append('<li>危険なシェル芸（危険シェル芸）は禁止</li>\n')
    lines.append('<li>余計な空白や改行は正誤判定に影響する可能性あり</li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>実行制限</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>実行時間 : 5.0s</li>\n')
    lines.append('<li>入出力文字数 : 1000</li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>実行環境</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>cat /etc/os-release</li>\n')
    lines.append('<li>echo $SHELL</li>\n')
    lines.append('<li>bash --version</li>\n')
    lines.append('<li>python3 -V</li>\n')
    lines.append('<li>g++ --version</li>\n')
    lines.append('</ul>\n')
    lines.append('</details>\n')
  if lang == "en":
    lines.append('<h2>Run</h2>\n')
    lines.append('<details>\n')
    lines.append('<summary>Attention</summary>\n')
    lines.append('<h3>Attention</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>Get Input : "cat input.txt"</li>\n')
    lines.append('<li>Output Image as "media/output.jpg"</li>\n')
    lines.append('<li>Output must match the expected output text and image.</li>\n')
    lines.append('<li>Dangerous shell-gei are prohibited.</li>\n')
    lines.append('<li>Extra white space or line breaks will affect correct/incorrect judgment.</li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>Limitations</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>Run time : 5.0s</li>\n')
    lines.append('<li>Number of characters (in/out) : 1000</li>\n')
    lines.append('</ul>\n')
    lines.append('<h3>Environment</h3>\n')
    lines.append('<ul>\n')
    lines.append('<li>cat /etc/os-release</li>\n')
    lines.append('<li>echo $SHELL</li>\n')
    lines.append('<li>bash --version</li>\n')
    lines.append('<li>python3 -V</li>\n')
    lines.append('<li>g++ --version</li>\n')
    lines.append('</ul>\n')
    lines.append('</details>\n')

  # command button
  lines.append('<details>\n')
  lines.append('<summary>Input buttons</summary>\n')
  # abcdefghijklmnopqrstuvwxyz
  lines.append('<div id="click-commands">\n')
  # a
  lines.append('<button class="command-button" id="command-awk">awk</button>\n')
  # c
  lines.append('<button class="command-button" id="command-cat">cat</button>\n')
  lines.append('<button class="command-button" id="command-convert">convert</button>\n')
  lines.append('<button class="command-button" id="command-cut">cut</button>\n')
  # e
  lines.append('<button class="command-button" id="command-echo">echo</button>\n')
  # f
  lines.append('<button class="command-button" id="command-ffmpeg">ffmpeg</button>\n')
  lines.append('<button class="command-button" id="command-find">find</button>\n')
  # g
  lines.append('<button class="command-button" id="command-grep">grep</button>\n')
  # l
  lines.append('<button class="command-button" id="command-ls">ls</button>\n')
  # p
  lines.append('<button class="command-button" id="command-ps">ps</button>\n')
  # s
  lines.append('<button class="command-button" id="command-sed">sed</button>\n')
  lines.append('<button class="command-button" id="command-seq">seq</button>\n')
  lines.append('<button class="command-button" id="command-sort">sort</button>\n')
  # t
  lines.append('<button class="command-button" id="command-tail">tail</button>\n')
  lines.append('<button class="command-button" id="command-textimg">textimg</button>\n')
  # u
  lines.append('<button class="command-button" id="command-uniq">uniq</button>\n')
  # w
  lines.append('<button class="command-button" id="command-wc">wc</button>\n')

  # other
  lines.append('<button class="command-button" id="command-space">SPACE</button>\n')
  lines.append('<button class="command-button" id="command-pipe"> | </button>\n')
  lines.append('<button class="command-button" id="command-hyphen"> - </button>\n')
  lines.append('<button class="command-button" id="command-plus"> + </button>\n')
  lines.append('<button class="command-button" id="command-equal"> = </button>\n')
  lines.append('<button class="command-button" id="command-under"> _ </button>\n')
  lines.append('<button class="command-button" id="command-exclamation"> ! </button>\n')
  lines.append('<button class="command-button" id="command-question"> ? </button>\n')
  lines.append('<button class="command-button" id="command-single-quote"> \' </button>\n')
  lines.append('<button class="command-button" id="command-double-quote"> " </button>\n')
  lines.append('<button class="command-button" id="command-back-quote"> ` </button>\n')
  lines.append('<button class="command-button" id="command-parentheses-left"> ( </button>\n')
  lines.append('<button class="command-button" id="command-parentheses-right"> ) </button>\n')
  lines.append('<button class="command-button" id="command-square-left"> [ </button>\n')
  lines.append('<button class="command-button" id="command-square-right"> ] </button>\n')
  lines.append('<button class="command-button" id="command-curly-left"> { </button>\n')
  lines.append('<button class="command-button" id="command-curly-right"> } </button>\n')
  lines.append('<button class="command-button" id="command-slash"> / </button>\n')
  lines.append('<button class="command-button" id="command-back-slash"> \\ </button>\n')
  lines.append('<button class="command-button" id="command-greater-then"> &gt; </button>\n')
  lines.append('<button class="command-button" id="command-less-then"> &lt; </button>\n')
  lines.append('<button class="command-button" id="command-asterisk"> * </button>\n')
  lines.append('<button class="command-button" id="command-dollar"> $ </button>\n')
  lines.append('<button class="command-button" id="command-at"> @ </button>\n')
  lines.append('<button class="command-button" id="command-dot"> . </button>\n')
  lines.append('<button class="command-button" id="command-comma"> , </button>\n')
  lines.append('<button class="command-button" id="command-sharp"> # </button>\n')
  lines.append('<button class="command-button" id="command-colon"> : </button>\n')
  lines.append('<button class="command-button" id="command-semicolon"> ; </button>\n')
  lines.append('<button class="command-button" id="command-and"> & </button>\n')
  lines.append('<button class="command-button" id="command-hat"> ^ </button>\n')
  lines.append('<button class="command-button" id="command-tilde"> ~ </button>\n')
  lines.append('<button class="command-button" id="command-per"> % </button>\n')

  lines.append('<button class="command-button" id="command-txt-path">input.txt</button>\n')
  lines.append('<button class="command-button" id="command-img-path">/media/output.jpg</button>\n')
  lines.append('<button class="command-button" id="command-gif-path">/media/output.gif</button>\n')
  lines.append('</div>\n')
  lines.append('</details>\n')
  # delete
  lines.append('<div id="click-commands">\n')
  lines.append('<button class="command-button-red" id="delete-command-one">delete one</button>\n')
  lines.append('<button class="command-button-red" id="delete-command-all">delete all</button>\n')
  lines.append('</div>\n')

  if lang == "jp":
    lines.append('<div class="centerClass">\n')
    lines.append('<textarea name="cmdline" cols="50" rows="12" id="cmdline" placeholder="ここにシェル芸を記述"></textarea>\n')
    lines.append('</div>\n')
    lines.append('<div class="centerClass">\n')
    lines.append('<input type="button" value="実行（Ctrl+Enter）" class="buttonClass_r" id="submitButton">\n')
    lines.append('</div>\n')
    lines.append('\n')
  if lang == "en":
    lines.append('<div class="centerClass">\n')
    lines.append('<textarea name="cmdline" cols="50" rows="12" id="cmdline" placeholder="Write your shell-gei here"></textarea>\n')
    lines.append('</div>\n')
    lines.append('<div class="centerClass">\n')
    lines.append('<input type="button" value="RUN (Ctrl+Enter)" class="buttonClass_r" id="submitButton">\n')
    lines.append('</div>\n')
    lines.append('\n')

  # result
  if lang == "jp":
    lines.append('<h2>結果</h2>\n')
    lines.append('<h3>正誤判定</h3>\n')
    lines.append('<div class="textClass">\n')
    lines.append('<pre><code id="resultText" class="mono-font">NULL</code></pre>\n')
    lines.append('</div>\n')
    lines.append('<h3>実行結果</h3>\n')
    lines.append('<div class="textClass">\n')
    lines.append('<pre><code id="userOutputText" class="mono-font">NULL</code></pre>\n')
    lines.append('</div>\n')
    lines.append('<h3>出力画像</h3>\n')
    lines.append('<div class="img" id="resultImage">\n')
    lines.append('</div>\n')
    lines.append('<h3>実行したシェル芸</h3>\n')
    lines.append('<div class="textClass">\n')
    lines.append('<pre><code id="shellgeiText" class="mono-font">NULL</code></pre>\n')
    lines.append('</div>\n')
    lines.append('\n')
  if lang == "en":
    lines.append('<h2>Result</h2>\n')
    lines.append('<h3>Judgment</h3>\n')
    lines.append('<div class="textClass">\n')
    lines.append('<pre><code id="resultText" class="mono-font">NULL</code></pre>\n')
    lines.append('</div>\n')
    lines.append('<h3>Output Result</h3>\n')
    lines.append('<div class="textClass">\n')
    lines.append('<pre><code id="userOutputText" class="mono-font">NULL</code></pre>\n')
    lines.append('</div>\n')
    lines.append('<h3>Output Image</h3>\n')
    lines.append('<div class="img" id="resultImage">\n')
    lines.append('</div>\n')
    lines.append('<h3>Executed Shell-gei</h3>\n')
    lines.append('<div class="textClass">\n')
    lines.append('<pre><code id="shellgeiText" class="mono-font">NULL</code></pre>\n')
    lines.append('</div>\n')
    lines.append('\n')

  # bottom
  lines.append('<hr class="BlackLine">\n')
  lines.append('<p></p>\n')
  lines.append('<div class="img">\n')
  lines.append('<img src="'+main_url+'/BlackTreeIcon.jpg">\n')
  lines.append('</div>\n')
  lines.append('<script>\n')
  if lang == "jp":
    lines.append('var is_jp = true;\n')
  if lang == "en":
    lines.append('var is_jp = false;\n')
  lines.append('</script>\n')
  lines.append('<script src="'+main_url+'/index.js'+version_str+'"></script>\n')
  lines.append('</div> <!-- alldiv -->\n')
  lines.append('<h1 class="heading-028-2" data-label="">GitHub - <a href="https://github.com/YusukeKato/ShellgeiOnlineJudge/discussions" class="white-link">SHELLGEI ONLINE JUDGE Discussions</a><br>&copy; 2023 YusukeKato All rights reserved.</h1>\n')
  lines.append('</body>\n')
  lines.append('</html>\n')

  # write
  if lang == "jp":
    with open('../html/index.html', 'w', encoding='UTF-8') as fw:
      fw.writelines(lines)
  if lang == "en":
    with open('../html/index.en.html', 'w', encoding='UTF-8') as fw:
      fw.writelines(lines)

# 書き込み実行
write_index_html("jp")
write_index_html("en")
