name: FastAPI CI

on:
  push:
  pull_request:
  schedule:
    - cron: "45 10 * * 2" # At 10:45 AM (UTC) every Tuesday.

jobs:
  linting_and_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run linting (ruff check)
        run: poetry run ruff check .

      - name: Run formatting check (ruff format)
        run: poetry run ruff format --check .
        
      - name: Run static type checking (mypy)
        run: poetry run mypy .